import { useEffect, useState } from "react";\nimport { useNavigate, useParams } from "react-router-dom";\nimport { accessCheck, startExam } from "../../api/student";\nimport { getErrorMessage } from "../../api/client";\nimport { detectDevice } from "../../utils/device";\nimport { ErrorBox } from "../../components/State";\nimport { clearBrokenStudentSession } from "../../utils/clearStudentSession";\n\nexport function WaitingRoomPage() {\n  const { examId = "" } = useParams();\n  const navigate = useNavigate();\n  const [exam, setExam] = useState<any>(null);\n  const [status, setStatus] = useState("checking");\n  const [error, setError] = useState("");\n  const [starting, setStarting] = useState(false);\n\n  async function load() {\n    try {\n      const savedCode = localStorage.getItem(`examCode:${examId}`) || undefined;\n      const data = await accessCheck(examId, savedCode);\n      setExam(data.exam);\n      setStatus(data.examStatus);\n    } catch (err) {\n      const message = getErrorMessage(err);
      if (message.includes("Session not found")) {
        clearBrokenStudentSession();
        window.location.href = "/student/exams";
        return;
      }
      setError(message);\n    }\n  }\n\n  useEffect(() => {\n    load();\n    const interval = window.setInterval(load, 5000);\n    return () => window.clearInterval(interval);\n  }, [examId]);\n\n  async function onStart() {\n    setStarting(true);\n    setError("");\n    try {\n      const device = detectDevice();\n      const examCode = localStorage.getItem(`examCode:${examId}`) || undefined;\n      const data = await startExam(examId, { ...device, examCode });\n      localStorage.setItem("currentSessionId", data.sessionId);\n      if (data.status === "submitted") navigate(`/student/conclusion/${data.sessionId}`);\n      else if (String(data.status).includes("banned")) navigate(`/student/banned/${data.sessionId}`);\n      else navigate(`/student/exam/${data.sessionId}`);\n    } catch (err) {\n      const message = getErrorMessage(err);
      if (message.includes("Session not found")) {
        clearBrokenStudentSession();
        window.location.href = "/student/exams";
        return;
      }
      setError(message);\n    } finally {\n      setStarting(false);\n    }\n  }\n\n  return (\n    <div className="student-centered">\n      <section className="exam-card narrow">\n        <h1>Хүлээлгийн өрөө</h1>\n        {error && <ErrorBox message={error} />}\n        <div className="summary-list">\n          <div><span>Шалгалт</span><strong>{exam?.title || "-"}</strong></div>\n          <div><span>Төлөв</span><strong>{status === "open" ? "Шалгалт нээлттэй" : "Багш эхлүүлэхийг хүлээж байна"}</strong></div>\n          <div><span>Нийт асуулт</span><strong>{exam?.totalQuestions || "-"}</strong></div>\n          <div><span>Асуулт бүрийн хугацаа</span><strong>{exam?.perQuestionTimeSeconds || "-"} сек</strong></div>\n          <div><span>Хүнд зөрчил</span><strong>3 удаа хүртэл анхааруулга, 4 дэх дээр түгжинэ</strong></div>\n        </div>\n        {status === "open" ? <button disabled={starting} onClick={onStart}>{starting ? "Эхлүүлж байна..." : "Шалгалт эхлүүлэх"}</button> : <p className="muted center">Та шалгалтад холбогдсон байна. Багш эхлүүлэх хүртэл энэ хуудсан дээр хүлээнэ үү. Төлөв 5 секунд тутамд автоматаар шинэчлэгдэнэ.</p>}\n      </section>\n    </div>\n  );\n}